apiVersion: v1
data:
  engineUrl: http://172.168.26.9
  envName: k8s-master
  groupName: K8S-Volumes
  mountPath: /mnt/provision
  repoName: "Kubernetes - default - v1.18.9+k3s1"
  sourceRef: APPDATA_CONTAINER-83
kind: ConfigMap
metadata:
  name: delphix-config
  namespace: kube-system
