Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "public_network", 
    use_dhcp_assigned_default_route: true
  config.vm.provider :vmware_desktop do |v|
      v.vmx["memsize"] = 2048
      v.vmx["numvcpus"] = 2
	v.ssh_info_public = true
        # https://github.com/hashicorp/vagrant/issues/12045
        v.gui = true
    end
  config.vm.provision "shell", inline: <<-EOF
    snap install microk8s --classic
    snap install docker
    microk8s.status --wait-ready
    microk8s.enable dns dashboard registry
    usermod -a -G microk8s vagrant
    echo "alias kubectl='microk8s.kubectl'" > /home/vagrant/.bash_aliases
    chown vagrant:vagrant /home/vagrant/.bash_aliases
    echo "alias kubectl='microk8s.kubectl'" > /root/.bash_aliases
    chown root:root /root/.bash_aliases
  EOF

  config.vm.define "microk8s_a" do |microk8s_a|
    microk8s_a.vm.hostname = "microk8s-a"
    microk8s_a.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
    microk8s_a.vm.provision "shell", inline: <<-EOF
      mkdir /vagrant && chown vagrant. /vagrant
      export local_ip="$(ip route | grep default | grep eth0 | cut -d' ' -f9)"
      microk8s.add-node | grep $local_ip | tee /vagrant/add_k8s
    EOF
  end
  config.vm.define "microk8s_b" do |microk8s_b|
    microk8s_b.vm.hostname = "microk8s-b"
    microk8s_b.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
    microk8s_b.vm.provision "shell", inline: <<-EOF
      bash -x /vagrant/add_k8s
    EOF
  end
end
