IMAGE_NAME = "centos/7"
#IMAGE_NAME = "generic/debian10"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false


    config.vm.provider :vmware_desktop do |v|
        v.vmx["memsize"] = 2048
        v.vmx["numvcpus"] = 2
	#v.vmx["ethernet0.pcislotnumber"] = "32"
        v.ssh_info_public = true
	# https://github.com/hashicorp/vagrant/issues/12045
        v.gui = true
    end
      
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
	#master.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
        master.vm.network "public_network", use_dhcp_assigned_default_route: true
        master.vm.network "private_network", ip: "172.168.26.10"
	
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "172.168.26.10",
		        uusername: "delphix",
		        upassword: "delphix",
                server_name: "k8s-master",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
	    node.vm.network "forwarded_port", guest: 22, host: 2222+i, id: "ssh", auto_correct: true
            node.vm.network "public_network", use_dhcp_assigned_default_route: true
            node.vm.network "private_network", ip: "172.168.26.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
        	        uusername: "delphix",
	                upassword: "delphix",
                    node_ip: "172.168.26.#{i + 10}",
                    master_ip: "172.168.26.10",
                    server_name: "node-#{i}",
                }
            end
        end
    end
end
