apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: csi-deployment-pvc-clone
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: de-fs-storage
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: csi-deployment-pvc
