apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-demo-source-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: de-fs-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox 
spec:
  containers:
  - image: busybox
    securityContext:
        runAsGroup: 1001
        runAsUser: 1001
    command:  ["sleep", "600"]
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
      - mountPath: /var/data
        name: csi-demo-volume
  volumes:
  - name: csi-demo-volume
    persistentVolumeClaim:
      claimName: csi-demo-source-pvc
