apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-demo-restore-pvc
spec:
  dataSource:
    name: csi-demo-source-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  storageClassName: de-fs-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-restore-1 
spec:
  containers:
  - image: busybox
    securityContext:
        runAsGroup: 1001
        runAsUser: 1001
    command:  ["sleep", "600"]
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
      - mountPath: /var/data
        name: csi-demo-volume
  volumes:
  - name: csi-demo-volume
    persistentVolumeClaim:
      claimName: csi-demo-restore-pvc
