apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-demo-pvc-restore-reference
  annotations: 
    sourceReference: APPDATA_CONTAINER-61
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: de-fs-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-restore-2
spec:
  containers:
  - image: busybox
    securityContext:
        runAsGroup: 1001
        runAsUser: 1001
    command:  ["sleep", "600"]
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
      - mountPath: /var/data
        name: csi-deployment-pvc
  volumes:
  - name: csi-demo-volume
    persistentVolumeClaim:
      claimName: csi-demo-pvc-restore-reference
