apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-de-pvc-restore
spec:
  dataSource:
    name: csi-de-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2 
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: csi-deployment-pvc
  volumes:
  - name: csi-deployment-pvc
    persistentVolumeClaim:
      claimName: csi-de-pvc-restore
