apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-deployment-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: de-fs-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: busybox
    securityContext:
        runAsGroup: 1001
        runAsUser: 1001
    command:  ["sleep", "600"]
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: csi-deployment-pvc
  volumes:
  - name: csi-deployment-pvc
    persistentVolumeClaim:
      claimName: csi-deployment-pvc
