apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-deployment-pvc2
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: de-fs-storage
  volumeName: csi-deployment-pv2
